import 'package:flutter/material.dart';

class AppLocalization extends ChangeNotifier {
  Locale _locale = const Locale('vi');

  Locale get locale => _locale;

  void setLocale(Locale locale) {
    if (_locale != locale) {
      _locale = locale;
      notifyListeners();
    }
  }

  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'welcome': 'Welcome Back',
      'login': 'Login',
      'email_hint': 'Email or Phone number',
      'password_hint': 'Password',
      'forgot_password': 'Forgot Password?',
      'social_continue': 'Continue with social media',
      'hey': 'Hey Bhavneet',
      'grab_ride': 'Grab your new ride now',
      'new_ride': 'New Ride',
      'home': 'Home',
      'office': 'Office',
      'where_heading': 'Where are you heading?',
      'pickup': 'Pickup',
      'destination': 'Destination',
      'find_cars': 'Find Cars',
      'select_dest': 'Select Dest.',
      'min': 'min',
      'account': 'Account',
      'total_rides': 'Total Rides',
      'this_month': 'This Month',
      'spent': 'Spent',
      'payment_methods': 'Payment Methods',
      'manage_cards': 'Manage cards & wallets',
      'safety': 'Safety',
      'emergency': 'Emergency contacts & settings',
      'help_support': 'Help & Support',
      'faq': 'FAQ & contact us',
      'sign_out': 'Sign Out',
      'log_out': 'Log out of your account',
      'select_car': 'Choose your ride',
      'economy': 'Economy',
      'premium': 'Comfort',
      'normal': 'Normal',
      'popular': 'Popular',
      'seats': 'Seats',
      'select_ride': 'Select Ride',
      'km': 'km',
      'cash': 'Cash',
      'promo': 'Promo',
      'booking_history': 'Booking History',
      'no_bookings': 'No bookings yet.',
      'select_car_before': 'Select a car before confirming your booking.',
      'total_price': 'Total Price',
      'confirm_booking': 'Confirm Booking',
      'confirm_error_msg': 'Please make sure you have a pickup, destination, and a selected car.',
      'base_price': 'Base Price',
      'selected': 'Selected',
      'select': 'Select',
    },
    'vi': {
      'welcome': 'Chào mừng quay lại',
      'login': 'Đăng nhập',
      'email_hint': 'Email hoặc số điện thoại',
      'password_hint': 'Mật khẩu',
      'forgot_password': 'Quên mật khẩu?',
      'social_continue': 'Tiếp tục với mạng xã hội',
      'hey': 'Chào Bhavneet',
      'grab_ride': 'Đặt chuyến xe ngay thôi',
      'new_ride': 'Chuyến mới',
      'home': 'Nhà',
      'office': 'Văn phòng',
      'where_heading': 'Bạn muốn đi đâu?',
      'pickup': 'Điểm đón',
      'destination': 'Điểm đến',
      'find_cars': 'Tìm xe',
      'select_dest': 'Chọn điểm đến',
      'min': 'phút',
      'account': 'Tài khoản',
      'total_rides': 'Tổng chuyến',
      'this_month': 'Tháng này',
      'spent': 'Chi tiêu',
      'payment_methods': 'Phương thức thanh toán',
      'manage_cards': 'Quản lý thẻ & ví',
      'safety': 'An toàn',
      'emergency': 'Liên hệ khẩn cấp & cài đặt',
      'help_support': 'Trợ giúp & hỗ trợ',
      'faq': 'Câu hỏi thường gặp & liên hệ',
      'sign_out': 'Đăng xuất',
      'log_out': 'Thoát khỏi tài khoản',
      'select_car': 'Chọn loại xe',
      'economy': 'Tiết kiệm',
      'premium': 'Cao cấp',
      'van_xl': 'Xe 7 chỗ',
      'register': 'Đăng ký',
      'full_name': 'Họ và tên',
      'have_account': 'Đã có tài khoản? Đăng nhập',
      'no_account': 'Chưa có tài khoản? Đăng ký',
      'normal': 'Thông thường',
      'popular': 'Phổ biến',
      'seats': 'Ghế',
      'select_ride': 'Chọn chuyến',
      'km': 'km',
      'cash': 'Tiền mặt',
      'promo': 'Khuyến mãi',
      'booking_history': 'Lịch sử đặt xe',
      'no_bookings': 'Chưa có chuyến xe nào.',
      'select_car_before': 'Vui lòng chọn xe trước khi xác nhận.',
      'total_price': 'Tổng cộng',
      'confirm_booking': 'Xác nhận đặt xe',
      'confirm_error_msg': 'Vui lòng đảm bảo bạn đã chọn điểm đón, điểm đến và loại xe.',
      'base_price': 'Giá mở cửa',
      'selected': 'Đã chọn',
      'select': 'Chọn',
    },
    'ja': {
      'welcome': 'おかえりなさい',
      'login': 'ログイン',
      'email_hint': 'メール hoặc số điện thoại',
      'password_hint': 'Mật khẩu',
      'forgot_password': 'Quên mật khẩu?',
      'social_continue': 'Tiếp tục với mạng xã hội',
      'hey': 'Chào Bhavneet',
      'grab_ride': 'Đặt chuyến xe ngay thôi',
      'new_ride': 'Chuyến mới',
      'home': 'Nhà',
      'office': 'Văn phòng',
      'where_heading': 'Bạn muốn đi đâu?',
      'pickup': 'Điểm đón',
      'destination': 'Điểm đến',
      'find_cars': 'Tìm xe',
      'select_dest': 'Chọn điểm đến',
      'min': 'phút',
      'account': 'Tài khoản',
      'total_rides': 'Tổng chuyến',
      'this_month': 'Tháng này',
      'spent': 'Chi tiêu',
      'payment_methods': 'Phương thức thanh toán',
      'manage_cards': 'Quản lý thẻ & ví',
      'safety': 'An toàn',
      'emergency': 'Liên hệ khẩn cấp & cài đặt',
      'help_support': 'Trợ giúp & hỗ trợ',
      'faq': 'Câu hỏi thường gặp & liên hệ',
      'sign_out': 'Đăng xuất',
      'log_out': 'Thoát khỏi tài khoản',
      'select_car': 'Chọn loại xe',
      'economy': 'Tiết kiệm',
      'premium': 'Cao cấp',
      'van_xl': 'Xe 7 chỗ',
      'register': 'Đăng ký',
      'full_name': 'Họ và tên',
      'have_account': 'Đã có tài khoản? Đăng nhập',
      'no_account': 'Chưa có tài khoản? Đăng ký',
      'normal': 'Thông thường',
      'popular': 'Phổ biến',
      'seats': 'Ghế',
      'select_ride': 'Chọn chuyến',
      'km': 'km',
      'cash': '現金',
      'promo': 'プロモ',
      'booking_history': '予約履歴',
      'no_bookings': 'まだ予約はありません。',
      'select_car_before': '予約を確定する前に車を選択してください。',
      'total_price': '合計金額',
      'confirm_booking': '予約を確定する',
      'confirm_error_msg': '乗車場所、目的地、選択した車があることを確認してください。',
      'base_price': '基本料金',
      'selected': '選択済み',
      'select': '選択する',
    },
  };

  String translate(String key) {
    return _localizedValues[_locale.languageCode]?[key] ?? key;
  }
}
